name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 10 }
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm ci:verify

  lighthouse:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 10 }
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm install
      # Install Chromium for Lighthouse
      - run: npx playwright install chromium
      - run: pnpm lh:routes
        env:
          LH_HEALTHCHECK_ATTEMPTS: '45'
          LH_HEALTHCHECK_DELAY_MS: '1000'
      # Optionally upload reports
      - uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: .reports/*.json
